# ==================================
# To see the DB;
# http://localhost:8091/h2-console
# ==================================


#Application Configuration
server:
  port: 8091

spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  
   datasource:
     url: jdbc:mysql://localhost:3306/finalweb?useTimezone=true&serverTimezone=UTC
     driverClassName: com.mysql.cj.jdbc.Driver

     platform: mysql
     username: root

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
